## Assignment research and write down 20 in built methods on pandas and 20 on numpy with examples each.

## A. 20 Pandas in-buit methods with examples

In [34]:
#first i have to import pandas and numpy

import pandas as pd
import numpy as np

In [35]:
print(pd.__version__)

1.4.2


In [36]:
print(np.__version__)

1.21.5


## 1) read_csv() method

In [37]:
#read_csv file

file = r"C:\Users\iwuan\OneDrive\Desktop\practice.csv"
df = pd.read_csv(file)
print(df.to_string())

    S/N  COURSE UNIT COURSE CODE                                COURSE TITLE   SCORE GRADE  GRADE VALUE  GPA
0     1            3   SPH 708.1                               Human Ecology  72.500     A            5   15
1     2            2   SPH 703.1                      Health Laws and Ethics  78.760     A            5   10
2     3            2   SPH 701.1       History of Medicine and Public Health  70.850     A            5   10
3     4            2   SPH 734.2                        ICT In Public Health  79.800     A            5   10
4     5            4   SPH 723.1               Introduction to Biostatistics  70.050     A            5   20
5     6            4   SPH 725.1  Introduction to Principles of Epidemiology  82.600     A            5   20
6     7            4   SPH 712.1                       Public Health Methods  79.800     A            5   20
7     8            3   SPH 726.2                       Healthcare In Nigeria  85.480     A            5   15
8     9            

## 2) head() method

In [38]:
#To view the first six rows of the dataset

df.head(6)

S/N  COURSE UNIT COURSE CODE                                COURSE TITLE  \
0    1            3   SPH 708.1                               Human Ecology   
1    2            2   SPH 703.1                      Health Laws and Ethics   
2    3            2   SPH 701.1       History of Medicine and Public Health   
3    4            2   SPH 734.2                        ICT In Public Health   
4    5            4   SPH 723.1               Introduction to Biostatistics   
5    6            4   SPH 725.1  Introduction to Principles of Epidemiology   

   SCORE GRADE  GRADE VALUE  GPA  
0  72.50     A            5   15  
1  78.76     A            5   10  
2  70.85     A            5   10  
3  79.80     A            5   10  
4  70.05     A            5   20  
5  82.60     A            5   20

## 3) type() method

In [39]:
#To verify the type of object created

type(df)

pandas.core.frame.DataFrame

## 4) dtypes() method

In [40]:
#To print the data types of each columns

df.dtypes

S/N               int64
COURSE UNIT       int64
COURSE CODE      object
COURSE TITLE     object
SCORE           float64
GRADE            object
GRADE VALUE       int64
GPA               int64
dtype: object

## 5) info() method

In [41]:
# To print missing value stats and datatypes

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11 entries, 0 to 10
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   S/N           11 non-null     int64  
 1   COURSE UNIT   11 non-null     int64  
 2   COURSE CODE   11 non-null     object 
 3   COURSE TITLE  11 non-null     object 
 4   SCORE         11 non-null     float64
 5   GRADE         11 non-null     object 
 6   GRADE VALUE   11 non-null     int64  
 7   GPA           11 non-null     int64  
dtypes: float64(1), int64(4), object(3)
memory usage: 832.0+ bytes


## 6) describe() method

In [42]:
#This prints standard statistics (mean, standard deviation,count, min, max) of every numeric value column

df.describe()

S/N  COURSE UNIT      SCORE  GRADE VALUE        GPA
count  11.000000    11.000000  11.000000    11.000000  11.000000
mean    6.000000     2.727273  73.779364     4.727273  13.090909
std     3.316625     0.904534   9.211799     0.646670   5.146932
min     1.000000     2.000000  52.600000     3.000000   6.000000
25%     3.500000     2.000000  70.450000     5.000000  10.000000
50%     6.000000     2.000000  73.333000     5.000000  10.000000
75%     8.500000     3.500000  79.800000     5.000000  17.500000
max    11.000000     4.000000  85.480000     5.000000  20.000000

## 7) iloc[] method

In [43]:
#This selects data by position (that is using the index number)
#I selected the first 5 rows of the data and index 3 to index 8 columns.

df.iloc[:5, 3:8]

COURSE TITLE  SCORE GRADE  GRADE VALUE  GPA
0                          Human Ecology  72.50     A            5   15
1                 Health Laws and Ethics  78.76     A            5   10
2  History of Medicine and Public Health  70.85     A            5   10
3                   ICT In Public Health  79.80     A            5   10
4          Introduction to Biostatistics  70.05     A            5   20

## 8) columns() method

In [44]:
#To view all the columns of a dataset

df.columns

Index(['S/N', 'COURSE UNIT', 'COURSE CODE', 'COURSE TITLE', 'SCORE', 'GRADE',
       'GRADE VALUE', 'GPA'],
      dtype='object')

## 9) drop() method

In [45]:
#To drop unwanted columns in the dataset

df = df.drop(columns = ['GRADE VALUE'])

In [50]:
#To confirm if the column "GRADE VALUE" has been dropped we print df

df

S/N  COURSE UNIT COURSE CODE                                COURSE TITLE  \
0     1            3   SPH 708.1                               Human Ecology   
1     2            2   SPH 703.1                      Health Laws and Ethics   
2     3            2   SPH 701.1       History of Medicine and Public Health   
3     4            2   SPH 734.2                        ICT In Public Health   
4     5            4   SPH 723.1               Introduction to Biostatistics   
5     6            4   SPH 725.1  Introduction to Principles of Epidemiology   
6     7            4   SPH 712.1                       Public Health Methods   
7     8            3   SPH 726.2                       Healthcare In Nigeria   
8     9            2   SPH 723.2                  Fundamentals of Demography   
9    10            2        SPH                                   Field Trip   
10   11            2   SPH 742.2                                     Seminar   

     SCORE GRADE  GPA  
0   72.500     A   15  
1   78.760     A   10  
2   70.850     A   10  
3   79.800     A   10  
4   70.050     A   20  
5   82.600     A   20  
6   79.800     A   20  
7   85.480     A   15  
8   65.800     B    8  
9   73.333     A   10  
10  52.600     C    6

## 10) len() method

In [27]:
#To check the length of the dataframe

len(df)

11

## 11) loc[] method

In [48]:
#It is similar to 'ilo[]' but here, the exact row index and column names we want is specified

df.loc[[2, 4, 6], ['COURSE UNIT', 'COURSE TITLE', 'SCORE', 'GRADE']]

COURSE UNIT                           COURSE TITLE  SCORE GRADE
2            2  History of Medicine and Public Health  70.85     A
4            4          Introduction to Biostatistics  70.05     A
6            4                  Public Health Methods  79.80     A

## 12) df.insert() method

In [59]:
#To insert random column in a specifies position. We will first create an array of random numbers that have the same length of our DataFrame
#This array will be inserted as a column in the df at column 7 position

random_col = np.random.randint(20, size = len(df))
df.insert(7, 'random_col',random_col)
df

S/N  COURSE UNIT COURSE CODE                                COURSE TITLE  \
0     1            3   SPH 708.1                               Human Ecology   
1     2            2   SPH 703.1                      Health Laws and Ethics   
2     3            2   SPH 701.1       History of Medicine and Public Health   
3     4            2   SPH 734.2                        ICT In Public Health   
4     5            4   SPH 723.1               Introduction to Biostatistics   
5     6            4   SPH 725.1  Introduction to Principles of Epidemiology   
6     7            4   SPH 712.1                       Public Health Methods   
7     8            3   SPH 726.2                       Healthcare In Nigeria   
8     9            2   SPH 723.2                  Fundamentals of Demography   
9    10            2        SPH                                   Field Trip   
10   11            2   SPH 742.2                                     Seminar   

     SCORE GRADE  GPA  random_col  
0   72.500     A   15           8  
1   78.760     A   10          18  
2   70.850     A   10           7  
3   79.800     A   10          16  
4   70.050     A   20           7  
5   82.600     A   20           7  
6   79.800     A   20           2  
7   85.480     A   15          10  
8   65.800     B    8          18  
9   73.333     A   10           0  
10  52.600     C    6          18

## 13) df["].cumsum () method

In [62]:
#This method calculates the cumulative sum of a data in a column.

df[['GPA']].cumsum()

GPA
0    15
1    25
2    35
3    45
4    65
5    85
6   105
7   120
8   128
9   138
10  144

## 14) df.sample () method

In [63]:
#When the size of the dataset is too big, a sample or fraction of the data can be taken for the analysis.

#exampe 1

df.sample(n = 5) 

S/N  COURSE UNIT COURSE CODE                                COURSE TITLE  \
6     7            4   SPH 712.1                       Public Health Methods   
5     6            4   SPH 725.1  Introduction to Principles of Epidemiology   
7     8            3   SPH 726.2                       Healthcare In Nigeria   
4     5            4   SPH 723.1               Introduction to Biostatistics   
10   11            2   SPH 742.2                                     Seminar   

    SCORE GRADE  GPA  random_col  
6   79.80     A   20           2  
5   82.60     A   20           7  
7   85.48     A   15          10  
4   70.05     A   20           7  
10  52.60     C    6          18

In [65]:
#example 2

df.sample(frac = 0.30)

S/N  COURSE UNIT COURSE CODE                                COURSE TITLE  \
4     5            4   SPH 723.1               Introduction to Biostatistics   
10   11            2   SPH 742.2                                     Seminar   
5     6            4   SPH 725.1  Introduction to Principles of Epidemiology   

    SCORE GRADE  GPA  random_col  
4   70.05     A   20           7  
10  52.60     C    6          18  
5   82.60     A   20           7

## 15)  df[‘’].where() method

In [71]:
#This function query a dataset based on a boolean condition. The random_col created previously has the values ranging from 0 to 20.

#example 1

df['random_col'].where(df['random_col'] < 15)

0      8.0
1      NaN
2      7.0
3      NaN
4      7.0
5      7.0
6      2.0
7     10.0
8      NaN
9      0.0
10     NaN
Name: random_col, dtype: float64

In [72]:
#in place of NaN, we replace it with 0

#example 2

df['random_col'].where(df['random_col'] < 15, 0)

0      8
1      0
2      7
3      0
4      7
5      7
6      2
7     10
8      0
9      0
10     0
Name: random_col, dtype: int32

## 16) df.memory_usage() method

In [73]:
# Memory usage of DataFrame columns.

df.memory_usage()

Index           128
S/N              88
COURSE UNIT      88
COURSE CODE      88
COURSE TITLE     88
SCORE            88
GRADE            88
GPA              88
random_col       44
dtype: int64

## 17)  df[‘’].unique() method

In [78]:
#This method is used to find out the unique values of a column. Preferrably a categorical column 

df.SCORE.unique()

array([72.5  , 78.76 , 70.85 , 79.8  , 70.05 , 82.6  , 85.48 , 65.8  ,
       73.333, 52.6  ])

## 18) df[‘’].nunique() method

In [79]:
#It shows how many unique values in a column.

df.SCORE.nunique()

10

## 19) df[‘’].rank() method

In [180]:
#It provides the rank of a selected column.

df['rank_col'] = df["GRADE"].rank()
df

S/N  COURSE UNIT COURSE CODE                                COURSE TITLE  \
0     1            3   SPH 708.1                               Human Ecology   
1     2            2   SPH 703.1                      Health Laws and Ethics   
2     3            2   SPH 701.1       History of Medicine and Public Health   
3     4            2   SPH 734.2                        ICT In Public Health   
4     5            4   SPH 723.1               Introduction to Biostatistics   
5     6            4   SPH 725.1  Introduction to Principles of Epidemiology   
6     7            4   SPH 712.1                       Public Health Methods   
7     8            3   SPH 726.2                       Healthcare In Nigeria   
8     9            2   SPH 723.2                  Fundamentals of Demography   
9    10            2        SPH                                   Field Trip   
10   11            2   SPH 742.2                                     Seminar   

     SCORE GRADE  GPA  random_col  rank_col  
0   72.500     A   15           8       5.0  
1   78.760     A   10          18       5.0  
2   70.850     A   10           7       5.0  
3   79.800     A   10          16       5.0  
4   70.050     A   20           7       5.0  
5   82.600     A   20           7       5.0  
6   79.800     A   20           2       5.0  
7   85.480     A   15          10       5.0  
8   65.800     B    8          18      10.0  
9   73.333     A   10           0       5.0  
10  52.600     C    6          18      11.0

## 20) df.count() method

In [95]:
#It gives the number of data in the DataFrame in the specified direction

df.count()

S/N             11
COURSE UNIT     11
COURSE CODE     11
COURSE TITLE    11
SCORE           11
GRADE           11
GPA             11
random_col      11
rank_calc       11
rank_col        11
rank_cal        11
dtype: int64

## B. 20 Numpy in-buit methods with examples

## 1) array ()

In [129]:
#It is used to create one-dimensional or multidimensional arrays from scratch.

see = np.array([2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24])
see

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24])

## 2) arange ()

In [113]:
#Return evenly spaced integer values over a given interval with some step size.

np.arange(4, 10, 2) #example 1

array([4, 6, 8])

In [114]:
np.arange(0,10) #example 2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [115]:
np.arange(5, 10, 15) #example 3

array([5])

## 3) uniform samples()

In [118]:
#Creates a random sample from a uniform distribution between lower and higher limit values.

np.random.uniform(10,20,size = 5)

array([17.13639102, 11.15671141, 19.53614129, 19.80513253, 10.43959258])

## 4) reshape()

In [137]:
#It shows an array having similar data with a new shape. 

see.reshape(6, 2)

array([[ 2,  4],
       [ 6,  8],
       [10, 12],
       [14, 16],
       [18, 20],
       [22, 24]])

## 5) linespace ()

In [119]:
#Shows an array with evenly spaced float numbers over a given interval.

np.linspace(15,50,5)

array([15.  , 23.75, 32.5 , 41.25, 50.  ])

## 6) array_split()

In [141]:
#It is used for splitting arrays, the array to split is passed and the number of splits.

new_fig = np.array_split(see, 3)
new_fig

[array([2, 4, 6, 8]), array([10, 12, 14, 16]), array([18, 20, 22, 24])]

## 7) repeat()

In [142]:
# it repeats the numbers in an array.

np.repeat(5,8)

array([5, 5, 5, 5, 5, 5, 5, 5])

## 8) dtype ()

In [143]:
#It returns the data type of an array.

see.dtype

dtype('int32')

## 9) array_sort()

In [144]:
#It sort a given array.

np.sort(see)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24])

## 10) unique ()

In [147]:
np.unique(see, return_counts = True)

(array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24]),
 array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int64))

## 11) expand dimensions ()

In [153]:
#It is used to expand the dimensions of an array.

np.expand_dims(see, axis = 1)

array([[ 2],
       [ 4],
       [ 6],
       [ 8],
       [10],
       [12],
       [14],
       [16],
       [18],
       [20],
       [22],
       [24]])

## 12) Count Non-Zero () 

In [154]:
np.count_nonzero(see)

12

## 13) where ()

In [164]:
#It shows an array for a certain value, and return the indexes that get a match.

z = np.where(see == 12)
print(z)

(array([5], dtype=int64),)


## 14) concatenate ()

In [165]:
#It joins arrays together

x = np.array ([1, 2, 3, 4])
x2 = np.array ([5, 6, 7, 8])
a = np.concatenate((x, x2))
print (a)

[1 2 3 4 5 6 7 8]


## 15) round ()

In [166]:
#It round float values to a specified number of decimal points.

b = np.random.random(size=(2,6))
print(b)

[[0.56955075 0.80804238 0.01748024 0.5983049  0.23429981 0.22713251]
 [0.68650655 0.16083911 0.13459403 0.28481334 0.00200157 0.19113417]]


## 16) put ()

In [188]:
#It replaces given elements of an array with values

arr = np.put(see, [2,3], [15,20])
print(see)

[ 2  6 15 20 10 12 14 16  7 20 22 24]


## 17) horizontal stacking hstack()

In [175]:
#It stack appends one array at the end of another

x = np.array ([1, 2, 3, 4])
x2 = np.array ([5, 6, 7, 8])

np.hstack((x,x2))

array([1, 2, 3, 4, 5, 6, 7, 8])

## 18) vertical stacking vstack()

In [176]:
#It stack one array on top of another

np.vstack((x,x2))

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

## 19) equal()

In [177]:
#It compares elements of arrays and if elements matched returns True, if not returns False
np.equal(x,x2)

array([False, False, False, False])

## 20) tile()

In [178]:
#It repeats an array the number of times given by reps

np.tile('Adanna', 6)

array(['Adanna', 'Adanna', 'Adanna', 'Adanna', 'Adanna', 'Adanna'],
      dtype='<U6')